language: python
python:
  - "2.7"

sudo: false

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

install:
  - (cd travis && source ./install_texlive.sh)

before_script:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH

script:
  - echo $PATH
  - make all
