language: python
python:
  - "3.6"

sudo: false

addons:
  apt:
    packages:
      - python-pygments

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/.cache/pip

install:
  - (cd travis && source ./install_texlive.sh)
  - pip install -r requirements.txt

before_script:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH

script:
  - make all
  - make notebooks
  - make index
